name: Docker Image Push

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    docker-push:
        runs-on: ubuntu-latest

        steps:
            -   name: Login to Docker Hub
                uses: docker/login-action@master
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and Push Docker image
                uses: docker/build-push-action@master
                with:
                    context: "{{defaultContext}}:app_python/"
                    push: true
                    tags: rekhlov/devops-flask-app:latest
